version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: host-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
      - ./momgo/log:/var/log/mongodb